name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for package.json
        id: check_pkg
        run: |
          if [ ! -f "package.json" ]; then
            echo "no_package=true" >> $GITHUB_OUTPUT
          else
            echo "no_package=false" >> $GITHUB_OUTPUT
          fi

      # 🔹 Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # 🔹 Installer pnpm globalement
      - name: Install pnpm globally
        run: npm i -g pnpm

      # 🔹 Installer les dépendances si package.json existe
      - name: Install dependencies

        run: npm i -g pnpm 

      # 🔹 Lancer ESLint et Prettier
      # - name: Run lint
      #  run: pnpm lint

      - name: Run Prettier format
        run: pnpm pretty

      # 🔹 Lancer les tests (inclut snapshot check)
        run: npm i -g pnpm 


        if: steps.check_pkg.outputs.no_package == 'false'
        run: pnpm install


